name: Code-Checks

on:
  push:
    branches:
      - "develop"

jobs:
  run-code-checks:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout repository
        uses: actions/checkout@v2
      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v1
      - name: Build application
        uses: docker/build-push-action@v2
        with:
          tags: chesshound
          target: bin
          load: true
          push: false
      - name: Build tests
        uses: docker/build-push-action@v2
        with:
          tags: chesshound-test
          target: test
          load: true
          push: false
      - name: Test application
        run: docker run chesshound-test
      - name: Build format container
        uses: docker/build-push-action@v2
        with:
          tags: chesshound-fmt
          target: fmt
          load: true
          push: false
      - name: Check source formatting
        run: docker run chesshound-fmt
