name: Continuous-Integration

on:
  push:
    branches:
      - "develop"

jobs:
  build-deploy:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout repository
        uses: actions/checkout@v2
      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v1
      - name: Build application
        id: docker_build_app
        uses: docker/build-push-action@v2
        with:
          tags: chesshound-test:latest
          load: true
          push: false
      - name: Test application
        run: docker run chesshound-test
