name: Code-Checks

on: [push]

jobs:
  run-code-checks:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout repository
        uses: actions/checkout@v2
      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v1
      - name: Build application
        uses: docker/build-push-action@v2
        with:
          tags: chesshound
          target: bin
          load: true
          push: false
      - name: Test application
        uses: grchristensen/docker-build-run@main
        with:
          target: test
      - name: Check source formatting
        uses: grchristensen/docker-build-run@main
        with:
          target: fmt
